name: unbiased_rec
channels:
  - maciejkula
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.6.10
  - click
  - numpy
  - pandas
  - python-dateutil
  - pickleshare
  - spotlight
  - scikit-learn
  - pytorch
  - scipy
